### PR TITLE
imap: bugfix - test connectivity oauth fix

### PR DESCRIPTION
**Pull request by jang-splunk**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

* Changed test_connectivity behavior to first check for existing OAuth token before calling new OAuth authenentication,
* add delete_oauth_token and refresh_oauth_token actions

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

test_connectivity starts new OAuth authentication process regardless of previous authentication status

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

test_connectivity will check for existing OAuth token and only start OAuth authentication if OAuth token is not found in state files.
new delete_oauth_token action provided to reset OAuth state to allow re-authentication
new refresh_access_token action provided

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by jang-splunk** [comment]
release notes need to change.

old:
add delete_oauth_token and refresh_oauth_token actions

new:
add delete_oauth_token and refresh_access_token actions

**Comment by jang-splunk** [comment]
cannot fix "action_coverage" and "app_actions" errors as changes are beyond the scope of this contributor.

all other tests has passed

**Comment by jang-splunk** [comment]
associated with [PAPP-31858 Update IMAP test connectivity to avoid manual re-authentication w…] and with Splunk Support case # 3304778

**Comment by aparekh-crest** [comment]
Hi @jang-splunk, 
Regarding this test connectivity change, It is not our best practice to use tokens from state file while running TC with OAuth, It should interact first with a user to authorise every time.

I have made some changes for OAuth in #18 PR , which can fix this ticket PAPP-31858 issue. In this #18 I have removed state file override issue while running test connectivity, so for now it will only update the state file if new tokens are available.

Let me know if you have concerns.

**Comment by aparekh-crest** [comment]
Hi @jang-splunk,
Can you explain me the use case of these two new actions?

`delete oauth token` action has been used for re-authentication from test connectivity, but as discussed in previous comment user has to interact for test connectivity. hence, this action is no longer required.

Same for `refresh access token` action, whenever access token expires it will generate new token from refresh token internally during other action executions I have implemented this logic in this #18 PR, so no requirement to create a separate action for this as well.

Let me know if you have any other inputs.

**Comment by jang-splunk** [comment]
> Hi @jang-splunk, Can you explain me the use case of these two new actions?
> 
> `delete oauth token` action has been used for re-authentication from test connectivity, but as discussed in previous comment user has to interact for test connectivity. hence, this action is no longer required.
> 
> Same for `refresh access token` action, whenever access token expires it will generate new token from refresh token internally during other action executions I have implemented this logic in this #18 PR, so no requirement to create a separate action for this as well.
> 
> Let me know if you have any other inputs.

The problem with this app is that test-connectivity mandates the re-authentication of the asset. This is a bad idea when the SOAR platform runs an automated test-connectivity every four hours to feed the widget in the home page.

So the first change i made is to only re-authenticate at test connectivity if it does not find an oauth token. You don't want it to re-authenticate if it fails to login to the imap server as that may be an network issue, and not a token issue.

Because test-connectivity should never re-authenticate, the "delete oauth token" action is required to manually delete the token and force test connectivity to re-authenticate.

The "refresh token" is there simply to test the oauth token's viability.

**Comment by jang-splunk** [comment]
> Hi @jang-splunk, Regarding this test connectivity change, It is not our best practice to use tokens from state file while running TC with OAuth, It should interact first with a user to authorise every time.
> 
> I have made some changes for OAuth in #18 PR , which can fix this ticket PAPP-31858 issue. In this #18 I have removed state file override issue while running test connectivity, so for now it will only update the state file if new tokens are available.
> 
> Let me know if you have concerns.

This "best practice" causes issues  as long as SOAR runs automated test connectivity actions every four hours. In fact it makes no sense at all since mandating an interaction completely disrupt the automated ingestion process.

As this app is primarily used to ingest emails to trigger playbooks, anything that disrupts that is a bad idea.

**Comment by jang-splunk** [comment]
In any case, PR#18 still mandates interactive authentication for oauth  irregardless of the current oath token state. This will break the asset health widget. I'm can't quite tell from your code whether or not this maintain the viability of the oauth token if the authentication fails, as it must when its invoked automatically for this widget.

**Comment by aparekh-crest** [comment]
@jang-splunk, Running Test-connectivity manually and running asset health automated by the platform are totally different and independent processes of soar and because of asset health we should not change the actual flow of execution in TC but what we can do is make changes which don't impact our existing tokens and credentials.

The actual issue is the automated asset health run will remove existing tokens from the state file which should not suppose to happen ideally.

As a workaround, it should not remove existing tokens from the state file so that it will not stop the automated ingestion process or playbook execution. that is regardless of asset health run. and it will not require these two new actions as well. 

That's what I have added in this #18

**Comment by aparekh-crest** [comment]
As per the discussion on Slack, Closing this PR as #18 will fix this PR issue.

**Pull request closed without merging**
